#pragma once
#include <ast/node.h>
#include <ast/integer.h>
#include <ast/infix.h>
#include <ast/bool.h>
#include <ast/expression_statement.h>
#include <ast/float.h>
#include <ast/prefix.h>
#include <ast/program.h>
#include <ast/string.h>
#include <ast/null.h>
#include <ast/identifier.h>
#include <ast/assign.h>
#include <ast/compound.h>
#include <ast/postfix.h>
#include <ast/ternary.h>
#include <ast/if.h>
#include <ast/while.h>
#include <ast/break.h>
#include <ast/continue.h>
#include <ast/for.h>
#include <ast/switch.h>
#include <ast/list.h>
#include <ast/index.h>
#include <ast/hash.h>
#include <ast/property.h>